---
# tasks file for roles/nginx
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true

- name: Disable default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Create Nginx configuration for Redmine
  ansible.builtin.copy:
    src: redmine
    dest: /etc/nginx/sites-available/redmine
    mode: '0744'
  notify: Reiniciar Nginx
