---
driver:
  name: docker
platforms:
  - name: ubuntu
    # you might want to add your own variables here based on what provisioning
    # you are doing like:
    image: ubuntu:22.04

provisioner:
  name: ansible
